export class Atenciones {
  public cliente!: string;
  public contacto!: string;
  public descripcion!: string;
  public estado!: string;
  public fechaC!: string;
  public fecha_creacion!: string;
  public id!: string;
  public motivoatencion!: string;
  public num_suministro!: string;
  public sistema!: string;
  public telefono!: string;
  public tipoatencion!: string;
  public titulo_atn!: string;
  public usuarioCreacion!: string;
  public nombre!: string;
  public conteo!: string;
public atencion_id!: string;
  public nomUsuario!:string;
  public id_tipo_atencion!:number;
  public id_motivo_atencion!:number;
  public fax!:string;
  public correo!:string;
  public whatsapp!:string;
  public user_id_evt!: number;
  public codigo_sucursal!: string;
  public representante!: string;
  public profesion!: string;
  public dui!: string;
  public nit!: string;
  public domicilio!: string;
  public departamento!: string;
  public cargo!: string;

  public ap_nombre!: string;
public ap_profesion!: string;
public ap_dui!: string;
public ap_nit!: string;
public ap_domicilio!: string;
public ap_departamento!: string;
public ap_actua!: string;
}
