export class Tickets {
  public analisisprelim!: string;
  public apellidoasignado!: string;
  public apellidosoli!: string;
  public categoria_id!: string;
  public comentarioaceptacion!: string;
  public comentariodenegado!: string;
  public comentariorechazo!: string;
  public comentarioresolucion!: string;
  public creador_ticket!: string;
  public created_at!: string;
  public desc_reasignacion!: string;
  public descripcion!: string;
  public estado!: string;
  public estado_id!: string;
  public evento_id!: string;
  public fechaaceptacion!: string;
  public fechacierre!: string;
  public fechaentregareal!: string;
  public fecharechazoticket!: string;
  public fechasolaprox!: string;
  public fechasolicitud!: string;
  public fechasolucion!: string;
  public id!: string;
  public idAte!: string;
  public modulo_id!: string;
  public nombreasignado!: string;
  public nombresoli!: string;
  public orden_id!: string;
  public reasignado!: string;
  public sistema_id!: string;
  public solucion!: string;
  public tiempodedicado!: string;
  public titulo!: string;
  public updated_at!: string;
  public us_asignado!: string;
  public us_solicitante!: string;
  public fecha_creacionD!: string;
  public atencion_id!: string;
  public fechasolaproxD!:string;
  public horaAproxD!:string;
  public asignado!:string;
  public solicitante!:string;
  public conteo!: string;
}
